language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/core-develop/.cache/pip
    - bower_components
    - node_modules


before_install:
  - git clone -b develop https://github.com/kbase/data_api.git core-develop
  - npm install -g bower
  - redis-server redis.conf &
 
install:
  - cd core-develop
  - pip install -r requirements.txt
  - python setup.py install -vv

before_script:
  - printf "Build dir = $TRAVIS_BUILD_DIR\n"
  - nohup data_api_start_service.py --service taxon --config deployment.cfg > taxonAPI.out &
  - nohup data_api_start_service.py --service assembly --config deployment.cfg > assemblyAPI.out &
#  - data_api_start_service.py --service genomeannotation --config deployment.cfg
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npm install
  - export PATH=`pwd`/node_modules/karma-cli/bin:`pwd`/node_modules/corsproxy/bin:$PATH
  - grunt build-travis
  - CORSPROXY_PORT=8000 corsproxy &

script:
  - karma start test/karma.conf.js

env:
  - KB_DEPLOY_URL="dir_cache"
  - KB_DEPLOY_URL="dir_nocache"
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
#  - codecov
  - kill $(cat taxonAPI.pid)
  - kill $(cat assemblyAPI.pid)
#  - kill $(cat genomeannotationAPI.pid)